"""add meditation session

Revision ID: 03b5f65b92db
Revises: 35e494ee9e18
Create Date: 2025-09-30 07:31:24.619834

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '03b5f65b92db'
down_revision = '35e494ee9e18'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('meditation_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('completed_duration', sa.Integer(), nullable=True),
    sa.Column('rating', sa.Integer(), nullable=True),
    sa.Column('session_note', sa.String(), nullable=True),
    sa.Column('session_timestamp', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('meditation_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['meditation_id'], ['meditations.id'], name=op.f('fk_meditation_sessions_meditation_id_meditations')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_meditation_sessions_user_id_users')),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('meditation_sessions')
    # ### end Alembic commands ###
