"""Add meditation table

Revision ID: 1a425cffe50d
Revises: 5fb818d8f1c6
Create Date: 2025-09-27 07:59:03.189522

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1a425cffe50d'
down_revision = '5fb818d8f1c6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('meditations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('duration', sa.Integer(), nullable=True),
    sa.Column('instructions', sa.String(), nullable=True),
    sa.Column('type', sa.Enum('Visualization', 'Body Scan', 'Lovingkindness', 'Mantra', 'Vipassana', name='meditation_type_enum'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('meditations')
    # ### end Alembic commands ###
